package com.test.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _EssayMappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _EssayMappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("wx_question_bank", "id", QuestionBank.class);
	}
}

