package com.test.model;

import com.test.model.base.BaseQuestionBank;

/**
 * Generated by JFinal.
 */
//@SuppressWarnings("serial")
public class QuestionBank extends BaseQuestionBank<QuestionBank> {
	public static final QuestionBank dao = new QuestionBank().dao();
	private String newType;
	private String newInfo;
	public String getnewType() {
		return newType;
	}
	public void setnewType(String newType) {
		this.newType = newType;
	}
	public String getnewInfo() {
		return newInfo;
	}
	public void setnewInfo(String newInfo) {
		this.newInfo = newInfo;
	}
	@Override
	public String toString() {
		return "QuestionBank [type=" + newType + ", info=" + newInfo + "]";
	}
	
}
