package com.test.model;

import com.test.model.base.BaseQuestionBank;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QuestionBank extends BaseQuestionBank<QuestionBank> {
	public static final QuestionBank dao = new QuestionBank().dao();
}
