package com.test.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePaper<M extends BasePaper<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setOpenid(java.lang.String openid) {
		set("openid", openid);
		return (M)this;
	}
	
	public java.lang.String getOpenid() {
		return getStr("openid");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	public M setPath(java.lang.String path) {
		set("path", path);
		return (M)this;
	}
	
	public java.lang.String getPath() {
		return getStr("path");
	}

	public M setStatus(java.lang.Long status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Long getStatus() {
		return getLong("status");
	}

	public M setUservote(java.lang.Long uservote) {
		set("uservote", uservote);
		return (M)this;
	}
	
	public java.lang.Long getUservote() {
		return getLong("uservote");
	}

	public M setCreationTime(java.util.Date creationTime) {
		set("creation_time", creationTime);
		return (M)this;
	}
	
	public java.util.Date getCreationTime() {
		return get("creation_time");
	}

	public M setCredentialsId(java.lang.Long credentialsId) {
		set("credentials_id", credentialsId);
		return (M)this;
	}
	
	public java.lang.Long getCredentialsId() {
		return getLong("credentials_id");
	}

	public M setExpertfraction(java.lang.Long expertfraction) {
		set("expertfraction", expertfraction);
		return (M)this;
	}
	
	public java.lang.Long getExpertfraction() {
		return getLong("expertfraction");
	}

}
