package com.test.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseActivityExplain<M extends BaseActivityExplain<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public M setBeginTime(java.util.Date beginTime) {
		set("begin_time", beginTime);
		return (M)this;
	}
	
	public java.util.Date getBeginTime() {
		return get("begin_time");
	}

	public M setEndTime(java.util.Date endTime) {
		set("end_time", endTime);
		return (M)this;
	}
	
	public java.util.Date getEndTime() {
		return get("end_time");
	}

	public M setShowCode(java.lang.Integer showCode) {
		set("showCode", showCode);
		return (M)this;
	}
	
	public java.lang.Integer getShowCode() {
		return getInt("showCode");
	}

	public M setParticipateClaim(java.lang.String participateClaim) {
		set("participateClaim", participateClaim);
		return (M)this;
	}
	
	public java.lang.String getParticipateClaim() {
		return getStr("participateClaim");
	}

	public M setWorksClaim(java.lang.String worksClaim) {
		set("worksClaim", worksClaim);
		return (M)this;
	}
	
	public java.lang.String getWorksClaim() {
		return getStr("worksClaim");
	}

	public M setParticipateManner(java.lang.String participateManner) {
		set("participateManner", participateManner);
		return (M)this;
	}
	
	public java.lang.String getParticipateManner() {
		return getStr("participateManner");
	}

}
