package com.test.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseQuestionBank<M extends BaseQuestionBank<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setType(java.lang.String type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}

	public M setInfo(java.lang.String info) {
		set("info", info);
		return (M)this;
	}
	
	public java.lang.String getInfo() {
		return getStr("info");
	}

	public M setAnalysis(java.lang.String analysis) {
		set("analysis", analysis);
		return (M)this;
	}
	
	public java.lang.String getAnalysis() {
		return getStr("analysis");
	}

	public M setStatus(java.lang.Boolean status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Boolean getStatus() {
		return get("status");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public M setCreateUser(java.lang.Integer createUser) {
		set("create_user", createUser);
		return (M)this;
	}
	
	public java.lang.Integer getCreateUser() {
		return getInt("create_user");
	}

	public M setUpdateUser(java.lang.Integer updateUser) {
		set("update_user", updateUser);
		return (M)this;
	}
	
	public java.lang.Integer getUpdateUser() {
		return getInt("update_user");
	}

}
